module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
];

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
];

module.exports.descriptions = [
    'Enveloped in dense foliage, offering a tranquil escape',
    'Steeped in history, with echoes of ancient civilizations',
    'Preserved in time, a testament to natural wonders',
    'Resounding with the powerful sounds of nature',
    'Cascading streams creating a symphony of water',
    'Gently tumbling down the mountainside',
    'Serenely quiet, inviting introspection',
    'Tower above with majestic presence',
    'A hub of activity amidst the wilderness',
    'Nestled under the shade of maple trees',
    'Mystical mist enveloping the landscape',
    'Home to majestic elk roaming freely',
    'Dominant and formidable, like the grizzly itself',
    'Where the ocean meets the land, a tranquil harmony',
    'A vast expanse of sea, stretching endlessly',
    'Open skies, offering a canvas of possibilities',
    'Blanketed in a fine layer of dust, untouched by time',
    'Like a precious gem, shimmering in the sunlight'
];
